// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAoyAiOJvE_RhNFzy1xVbVQxKD3S6Y4bI',
    appId: '1:751106603751:web:a71b77fb7f79e1cc054042',
    messagingSenderId: '751106603751',
    projectId: 'myproprtyapp',
    authDomain: 'myproprtyapp.firebaseapp.com',
    storageBucket: 'myproprtyapp.appspot.com',
    measurementId: 'G-8G9CCVVK5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBztRRipC_iphdthHupjYSm4FNBm4HVqMs',
    appId: '1:751106603751:android:dba0b964c0824452054042',
    messagingSenderId: '751106603751',
    projectId: 'myproprtyapp',
    storageBucket: 'myproprtyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuQzCumomCllB-nTX2YgthfkXFLQMdOIc',
    appId: '1:751106603751:ios:6cdf8edeea46c3c3054042',
    messagingSenderId: '751106603751',
    projectId: 'myproprtyapp',
    storageBucket: 'myproprtyapp.appspot.com',
    iosBundleId: 'com.example.propertyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeIPIh-kxXkmztapIJFTLLbnxIJHWdTTs',
    appId: '1:401208853653:ios:d292b87c71a20d5a06c79c',
    messagingSenderId: '401208853653',
    projectId: 'propertyapp-e753d',
    storageBucket: 'propertyapp-e753d.appspot.com',
    iosBundleId: 'com.example.propertyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAoyAiOJvE_RhNFzy1xVbVQxKD3S6Y4bI',
    appId: '1:751106603751:web:538ae601ea9c139b054042',
    messagingSenderId: '751106603751',
    projectId: 'myproprtyapp',
    authDomain: 'myproprtyapp.firebaseapp.com',
    storageBucket: 'myproprtyapp.appspot.com',
    measurementId: 'G-T1LN1Z2Q52',
  );

}